"""
HSK word list organized by level 1-6.
Each word: {"hanzi": str, "pinyin": str, "meaning": str, "hsk_level": int}
"""

HSK_WORDS = {
    1: [
    {'hanzi': '爱', 'pinyin': 'ài', 'meaning': 'yêu', 'hsk_level': 1},
    {'hanzi': '八', 'pinyin': 'bā', 'meaning': 'tám', 'hsk_level': 1},
    {'hanzi': '爸爸', 'pinyin': 'bàba', 'meaning': 'bố', 'hsk_level': 1},
    {'hanzi': '吧', 'pinyin': 'ba', 'meaning': 'trợ từ nghi vấn', 'hsk_level': 1},
    {'hanzi': '白天', 'pinyin': 'báitiān', 'meaning': 'sáng', 'hsk_level': 1},
    {'hanzi': '百', 'pinyin': 'bǎi', 'meaning': 'trăm', 'hsk_level': 1},
    {'hanzi': '包子', 'pinyin': 'bāozi', 'meaning': 'bánh bao', 'hsk_level': 1},
    {'hanzi': '杯子', 'pinyin': 'bēizi', 'meaning': 'cốc', 'hsk_level': 1},
    {'hanzi': '本', 'pinyin': 'běn', 'meaning': 'bản', 'hsk_level': 1},
    {'hanzi': '边', 'pinyin': 'biān', 'meaning': 'biên', 'hsk_level': 1},
    {'hanzi': '病', 'pinyin': 'bìng', 'meaning': 'bệnh', 'hsk_level': 1},
    {'hanzi': '不', 'pinyin': 'bù', 'meaning': 'không', 'hsk_level': 1},
    {'hanzi': '不客气', 'pinyin': 'bú', 'meaning': 'không có gì (đáp lại lời cảm ơn)', 'hsk_level': 1},
    {'hanzi': '不要', 'pinyin': 'búyào', 'meaning': 'không muốn', 'hsk_level': 1},
    {'hanzi': '菜', 'pinyin': 'cài', 'meaning': 'món ăn, rau củ', 'hsk_level': 1},
    {'hanzi': '茶', 'pinyin': 'chá', 'meaning': 'trà', 'hsk_level': 1},
    {'hanzi': '超市', 'pinyin': 'chāoshì', 'meaning': 'siêu thị', 'hsk_level': 1},
    {'hanzi': '车', 'pinyin': 'chē', 'meaning': 'ô tô', 'hsk_level': 1},
    {'hanzi': '吃', 'pinyin': 'chī', 'meaning': 'ăn', 'hsk_level': 1},
    {'hanzi': '出租车', 'pinyin': 'chūzūchē', 'meaning': 'taxi', 'hsk_level': 1},
    {'hanzi': '穿', 'pinyin': 'chuān', 'meaning': 'đeo', 'hsk_level': 1},
    {'hanzi': '打电话', 'pinyin': 'dǎ', 'meaning': 'gọi điện thoại', 'hsk_level': 1},
    {'hanzi': '大', 'pinyin': 'dà', 'meaning': 'lớn, to', 'hsk_level': 1},
    {'hanzi': '大家', 'pinyin': 'dàjiā', 'meaning': 'tất cả mọi người', 'hsk_level': 1},
    {'hanzi': '大学生', 'pinyin': 'dàxuéshēng', 'meaning': 'sinh viên đại học', 'hsk_level': 1},
    {'hanzi': '到', 'pinyin': 'dào', 'meaning': 'đến', 'hsk_level': 1},
    {'hanzi': '的', 'pinyin': 'de', 'meaning': 'của (thuộc tính)', 'hsk_level': 1},
    {'hanzi': '第', 'pinyin': 'dì', 'meaning': 'số thứ', 'hsk_level': 1},
    {'hanzi': '弟弟', 'pinyin': 'dìdi', 'meaning': 'anh em trai', 'hsk_level': 1},
    {'hanzi': '点', 'pinyin': 'diǎn', 'meaning': 'điểm', 'hsk_level': 1},
    {'hanzi': '店', 'pinyin': 'diàn', 'meaning': 'cửa hàng', 'hsk_level': 1},
    {'hanzi': '电话', 'pinyin': 'diànhuà', 'meaning': 'điện thoại', 'hsk_level': 1},
    {'hanzi': '电脑', 'pinyin': 'diànnǎo', 'meaning': 'máy tính', 'hsk_level': 1},
    {'hanzi': '电视', 'pinyin': 'diànshì', 'meaning': 'ti vi', 'hsk_level': 1},
    {'hanzi': '电影', 'pinyin': 'diànyǐng', 'meaning': 'phim', 'hsk_level': 1},
    {'hanzi': '电影院', 'pinyin': 'diànyǐngyuàn', 'meaning': 'rạp chiếu phim', 'hsk_level': 1},
    {'hanzi': '东西', 'pinyin': 'dōngxi', 'meaning': 'đồ vật, thứ', 'hsk_level': 1},
    {'hanzi': '都', 'pinyin': 'dōu', 'meaning': 'đều', 'hsk_level': 1},
    {'hanzi': '读', 'pinyin': 'dú', 'meaning': 'đọc', 'hsk_level': 1},
    {'hanzi': '读书', 'pinyin': 'dúshū', 'meaning': 'đọc sách', 'hsk_level': 1},
    {'hanzi': '对', 'pinyin': 'duì', 'meaning': 'đối', 'hsk_level': 1},
    {'hanzi': '对不起', 'pinyin': 'duìbuqǐ', 'meaning': 'xin lỗi', 'hsk_level': 1},
    {'hanzi': '多', 'pinyin': 'duō', 'meaning': 'nhiều', 'hsk_level': 1},
    {'hanzi': '儿子', 'pinyin': 'érzi', 'meaning': 'con trai', 'hsk_level': 1},
    {'hanzi': '二', 'pinyin': 'èr', 'meaning': 'hai', 'hsk_level': 1},
    {'hanzi': '饭', 'pinyin': 'fàn', 'meaning': 'bữa ăn', 'hsk_level': 1},
    {'hanzi': '饭店', 'pinyin': 'fàndiàn', 'meaning': 'quán ăn', 'hsk_level': 1},
    {'hanzi': '房间', 'pinyin': 'fángjiān', 'meaning': 'phòng', 'hsk_level': 1},
    {'hanzi': '非常', 'pinyin': 'fēicháng', 'meaning': 'rất', 'hsk_level': 1},
    {'hanzi': '飞机', 'pinyin': 'fēijī', 'meaning': 'máy bay', 'hsk_level': 1},
    {'hanzi': '分', 'pinyin': 'fēn', 'meaning': 'phần', 'hsk_level': 1},
    {'hanzi': '分钟', 'pinyin': 'fēnzhōng', 'meaning': 'phút', 'hsk_level': 1},
    {'hanzi': '高兴', 'pinyin': 'gāoxìng', 'meaning': 'vui', 'hsk_level': 1},
    {'hanzi': '哥哥', 'pinyin': 'gēge', 'meaning': 'anh trai', 'hsk_level': 1},
    {'hanzi': '个', 'pinyin': 'gè', 'meaning': 'cái (đơn vị lượng từ)', 'hsk_level': 1},
    {'hanzi': '给', 'pinyin': 'gěi', 'meaning': 'trả', 'hsk_level': 1},
    {'hanzi': '公司', 'pinyin': 'gōngsī', 'meaning': 'công ty', 'hsk_level': 1},
    {'hanzi': '工作', 'pinyin': 'gōngzuò', 'meaning': 'công việc', 'hsk_level': 1},
    {'hanzi': '狗', 'pinyin': 'gǒu', 'meaning': 'chó', 'hsk_level': 1},
    {'hanzi': '贵', 'pinyin': 'guì', 'meaning': 'đắt', 'hsk_level': 1},
    {'hanzi': '孩子', 'pinyin': 'háizi', 'meaning': 'con', 'hsk_level': 1},
    {'hanzi': '语', 'pinyin': 'Hànyǔ', 'meaning': 'tiếng Hán', 'hsk_level': 1},
    {'hanzi': '字', 'pinyin': 'Hànzì', 'meaning': 'chữ Hán', 'hsk_level': 1},
    {'hanzi': '好', 'pinyin': 'hǎo', 'meaning': 'tốt, khỏe', 'hsk_level': 1},
    {'hanzi': '好吃', 'pinyin': 'hǎochī', 'meaning': 'thích ăn', 'hsk_level': 1},
    {'hanzi': '好看', 'pinyin': 'hǎokàn', 'meaning': 'thích xem', 'hsk_level': 1},
    {'hanzi': '好听', 'pinyin': 'hǎotīng', 'meaning': 'thích nghe', 'hsk_level': 1},
    {'hanzi': '好玩儿', 'pinyin': 'hǎowánr', 'meaning': 'thích chơi', 'hsk_level': 1},
    {'hanzi': '号', 'pinyin': 'hào', 'meaning': 'số, ngày tháng', 'hsk_level': 1},
    {'hanzi': '喝', 'pinyin': 'hē', 'meaning': 'uống', 'hsk_level': 1},
    {'hanzi': '和', 'pinyin': 'hé', 'meaning': 'hợp nhất', 'hsk_level': 1},
    {'hanzi': '很', 'pinyin': 'hěn', 'meaning': 'rất', 'hsk_level': 1},
    {'hanzi': '后', 'pinyin': 'hòu', 'meaning': 'sau', 'hsk_level': 1},
    {'hanzi': '回', 'pinyin': 'huí', 'meaning': 'quay lại, về', 'hsk_level': 1},
    {'hanzi': '会', 'pinyin': 'huì', 'meaning': 'hội', 'hsk_level': 1},
    {'hanzi': '火车', 'pinyin': 'huǒchē', 'meaning': 'tàu lửa', 'hsk_level': 1},
    {'hanzi': '鸡蛋', 'pinyin': 'jīdàn', 'meaning': 'trứng', 'hsk_level': 1},
    {'hanzi': '几', 'pinyin': 'jǐ', 'meaning': 'mấy', 'hsk_level': 1},
    {'hanzi': '家', 'pinyin': 'jiā', 'meaning': 'gia đình, nhà', 'hsk_level': 1},
    {'hanzi': '见', 'pinyin': 'jiàn', 'meaning': 'nhìn thấy', 'hsk_level': 1},
    {'hanzi': '件', 'pinyin': 'jiàn', 'meaning': 'vật', 'hsk_level': 1},
    {'hanzi': '饺子', 'pinyin': 'jiǎozi', 'meaning': 'bánh bao', 'hsk_level': 1},
    {'hanzi': '叫', 'pinyin': 'jiào', 'meaning': 'gọi, tên gọi', 'hsk_level': 1},
    {'hanzi': '姐姐', 'pinyin': 'jiějie', 'meaning': 'chị gái', 'hsk_level': 1},
    {'hanzi': '今年', 'pinyin': 'jīnnián', 'meaning': 'năm nay', 'hsk_level': 1},
    {'hanzi': '今天', 'pinyin': 'jīntiān', 'meaning': 'hôm nay', 'hsk_level': 1},
    {'hanzi': '九', 'pinyin': 'jiǔ', 'meaning': 'chín', 'hsk_level': 1},
    {'hanzi': '觉得', 'pinyin': 'juéde', 'meaning': 'nhìn thấy', 'hsk_level': 1},
    {'hanzi': '开', 'pinyin': 'kāi', 'meaning': 'mở, khởi động', 'hsk_level': 1},
    {'hanzi': '看', 'pinyin': 'kàn', 'meaning': 'xem', 'hsk_level': 1},
    {'hanzi': '看病', 'pinyin': 'kànbìng', 'meaning': 'đi khám bệnh', 'hsk_level': 1},
    {'hanzi': '看见', 'pinyin': 'kànjiàn', 'meaning': 'nhìn thấy', 'hsk_level': 1},
    {'hanzi': '可以', 'pinyin': 'kěyǐ', 'meaning': 'có thể', 'hsk_level': 1},
    {'hanzi': '课', 'pinyin': 'kè', 'meaning': 'lớp học', 'hsk_level': 1},
    {'hanzi': '口', 'pinyin': 'kǒu', 'meaning': 'mồm', 'hsk_level': 1},
    {'hanzi': '块', 'pinyin': 'kuài', 'meaning': 'miếng, đồng (tiền)', 'hsk_level': 1},
    {'hanzi': '来', 'pinyin': 'lái', 'meaning': 'đến', 'hsk_level': 1},
    {'hanzi': '了', 'pinyin': 'le', 'meaning': 'đã (dùng để chỉ sự thay đổi)', 'hsk_level': 1},
    {'hanzi': '冷', 'pinyin': 'lěng', 'meaning': 'lạnh', 'hsk_level': 1},
    {'hanzi': '里', 'pinyin': 'lǐ', 'meaning': 'trong', 'hsk_level': 1},
    {'hanzi': '两', 'pinyin': 'liǎng', 'meaning': 'hai', 'hsk_level': 1},
    {'hanzi': '零', 'pinyin': 'líng', 'meaning': 'không (số 0)', 'hsk_level': 1},
    {'hanzi': '六', 'pinyin': 'liù', 'meaning': 'sáu', 'hsk_level': 1},
    {'hanzi': '妈妈', 'pinyin': 'māma', 'meaning': 'mẹ', 'hsk_level': 1},
    {'hanzi': '吗', 'pinyin': 'ma', 'meaning': 'không (dùng trong câu hỏi)', 'hsk_level': 1},
    {'hanzi': '买', 'pinyin': 'mǎi', 'meaning': 'mua', 'hsk_level': 1},
    {'hanzi': '卖', 'pinyin': 'mài', 'meaning': 'bán', 'hsk_level': 1},
    {'hanzi': '忙', 'pinyin': 'máng', 'meaning': 'bận rộn', 'hsk_level': 1},
    {'hanzi': '猫', 'pinyin': 'māo', 'meaning': 'mèo', 'hsk_level': 1},
    {'hanzi': '没关系', 'pinyin': 'méi', 'meaning': 'không sao, không có gì', 'hsk_level': 1},
    {'hanzi': '没事', 'pinyin': 'méishì', 'meaning': 'không có việc', 'hsk_level': 1},
    {'hanzi': '没有', 'pinyin': 'méiyǒu', 'meaning': 'không có', 'hsk_level': 1},
    {'hanzi': '妹妹', 'pinyin': 'mèimei', 'meaning': 'em gái', 'hsk_level': 1},
    {'hanzi': '们', 'pinyin': 'men', 'meaning': 'các người', 'hsk_level': 1},
    {'hanzi': '米饭', 'pinyin': 'mǐfàn', 'meaning': 'cơm', 'hsk_level': 1},
    {'hanzi': '面包', 'pinyin': 'miànbāo', 'meaning': 'bánh mì', 'hsk_level': 1},
    {'hanzi': '明年', 'pinyin': 'míngnián', 'meaning': 'năm sau', 'hsk_level': 1},
    {'hanzi': '明天', 'pinyin': 'míngtiān', 'meaning': 'ngày mai', 'hsk_level': 1},
    {'hanzi': '名字', 'pinyin': 'míngzi', 'meaning': 'tên', 'hsk_level': 1},
    {'hanzi': '哪', 'pinyin': 'nǎ', 'meaning': 'đâu', 'hsk_level': 1},
    {'hanzi': '哪个', 'pinyin': 'nǎge', 'meaning': 'đâu đó', 'hsk_level': 1},
    {'hanzi': '哪里', 'pinyin': 'nǎlǐ', 'meaning': 'ở đâu', 'hsk_level': 1},
    {'hanzi': '哪儿', 'pinyin': 'nǎr', 'meaning': 'ở đâu', 'hsk_level': 1},
    {'hanzi': '哪些', 'pinyin': 'nǎxiē', 'meaning': 'các', 'hsk_level': 1},
    {'hanzi': '那', 'pinyin': 'nà', 'meaning': 'đó, kia', 'hsk_level': 1},
    {'hanzi': '那边', 'pinyin': 'nàbiān', 'meaning': 'phía đó', 'hsk_level': 1},
    {'hanzi': '那里', 'pinyin': 'nàlǐ', 'meaning': 'ở đó', 'hsk_level': 1},
    {'hanzi': '那儿', 'pinyin': 'nàr', 'meaning': 'ở đó', 'hsk_level': 1},
    {'hanzi': '那些', 'pinyin': 'nàxiē', 'meaning': 'các', 'hsk_level': 1},
    {'hanzi': '男', 'pinyin': 'nán', 'meaning': 'nam', 'hsk_level': 1},
    {'hanzi': '男朋友', 'pinyin': 'nánpéngyou', 'meaning': 'chàng trai', 'hsk_level': 1},
    {'hanzi': '呢', 'pinyin': 'ne', 'meaning': 'thì sao? (dùng để hỏi thêm)', 'hsk_level': 1},
    {'hanzi': '能', 'pinyin': 'néng', 'meaning': 'có thể', 'hsk_level': 1},
    {'hanzi': '你', 'pinyin': 'nǐ', 'meaning': 'bạn', 'hsk_level': 1},
    {'hanzi': '你们', 'pinyin': 'nǐmen', 'meaning': 'các bạn', 'hsk_level': 1},
    {'hanzi': '年', 'pinyin': 'nián', 'meaning': 'năm', 'hsk_level': 1},
    {'hanzi': '您', 'pinyin': 'nín', 'meaning': 'bạn', 'hsk_level': 1},
    {'hanzi': '牛奶', 'pinyin': 'niúnǎi', 'meaning': 'sữa bò', 'hsk_level': 1},
    {'hanzi': '女', 'pinyin': 'nǚ', 'meaning': 'nữ', 'hsk_level': 1},
    {'hanzi': '女朋友', 'pinyin': 'nǚpéngyou', 'meaning': 'bạn gái', 'hsk_level': 1},
    {'hanzi': '女士', 'pinyin': 'nǚshì', 'meaning': 'phụ nữ, bà', 'hsk_level': 1},
    {'hanzi': '朋友', 'pinyin': 'péngyou', 'meaning': 'bạn', 'hsk_level': 1},
    {'hanzi': '便宜', 'pinyin': 'piányi', 'meaning': 'rẻ', 'hsk_level': 1},
    {'hanzi': '漂亮', 'pinyin': 'piàoliang', 'meaning': 'đẹp', 'hsk_level': 1},
    {'hanzi': '苹果', 'pinyin': 'píngguǒ', 'meaning': 'táo', 'hsk_level': 1},
    {'hanzi': '七', 'pinyin': 'qī', 'meaning': 'bảy', 'hsk_level': 1},
    {'hanzi': '起床', 'pinyin': 'qǐchuáng', 'meaning': 'thức dậy', 'hsk_level': 1},
    {'hanzi': '千', 'pinyin': 'qiān', 'meaning': 'nghìn', 'hsk_level': 1},
    {'hanzi': '前', 'pinyin': 'qián', 'meaning': 'phía trước', 'hsk_level': 1},
    {'hanzi': '钱', 'pinyin': 'qián', 'meaning': 'tiền', 'hsk_level': 1},
    {'hanzi': '请', 'pinyin': 'qǐng', 'meaning': 'xin vui lòng, mời', 'hsk_level': 1},
    {'hanzi': '请问', 'pinyin': 'qǐngwèn', 'meaning': 'xin hỏi', 'hsk_level': 1},
    {'hanzi': '去年', 'pinyin': 'qùnián', 'meaning': 'năm ngoái', 'hsk_level': 1},
    {'hanzi': '热', 'pinyin': 'rè', 'meaning': 'nóng', 'hsk_level': 1},
    {'hanzi': '人', 'pinyin': 'rén', 'meaning': 'người', 'hsk_level': 1},
    {'hanzi': '认识', 'pinyin': 'rènshi', 'meaning': 'quen biết', 'hsk_level': 1},
    {'hanzi': '日', 'pinyin': 'rì', 'meaning': 'ngày', 'hsk_level': 1},
    {'hanzi': '三', 'pinyin': 'sān', 'meaning': 'ba', 'hsk_level': 1},
    {'hanzi': '商店', 'pinyin': 'shāngdiàn', 'meaning': 'cửa hàng', 'hsk_level': 1},
    {'hanzi': '上', 'pinyin': 'shàng', 'meaning': 'lên', 'hsk_level': 1},
    {'hanzi': '上班', 'pinyin': 'shàngbān', 'meaning': 'đi làm', 'hsk_level': 1},
    {'hanzi': '上课', 'pinyin': 'shàngkè', 'meaning': 'lên lớp', 'hsk_level': 1},
    {'hanzi': '上学', 'pinyin': 'shàngxué', 'meaning': 'đi học', 'hsk_level': 1},
    {'hanzi': '少', 'pinyin': 'shǎo', 'meaning': 'ít', 'hsk_level': 1},
    {'hanzi': '谁', 'pinyin': 'shéi/shuí', 'meaning': 'ai', 'hsk_level': 1},
    {'hanzi': '什么', 'pinyin': 'shénme', 'meaning': 'cái gì', 'hsk_level': 1},
    {'hanzi': '生病', 'pinyin': 'shēngbìng', 'meaning': 'bị bệnh', 'hsk_level': 1},
    {'hanzi': '十', 'pinyin': 'shí', 'meaning': 'mười', 'hsk_level': 1},
    {'hanzi': '时候', 'pinyin': 'shíhou', 'meaning': 'lúc, khi', 'hsk_level': 1},
    {'hanzi': '时间', 'pinyin': 'shíjiān', 'meaning': 'thời gian', 'hsk_level': 1},
    {'hanzi': '是', 'pinyin': 'shì', 'meaning': 'là, thì', 'hsk_level': 1},
    {'hanzi': '手机', 'pinyin': 'shǒujī', 'meaning': 'điện thoại', 'hsk_level': 1},
    {'hanzi': '书', 'pinyin': 'shū', 'meaning': 'sách', 'hsk_level': 1},
    {'hanzi': '书店', 'pinyin': 'shūdiàn', 'meaning': 'hiệu sách', 'hsk_level': 1},
    {'hanzi': '水', 'pinyin': 'shuǐ', 'meaning': 'nước', 'hsk_level': 1},
    {'hanzi': '水果', 'pinyin': 'shuǐguǒ', 'meaning': 'trái cây', 'hsk_level': 1},
    {'hanzi': '睡', 'pinyin': 'shuì', 'meaning': 'ngủ', 'hsk_level': 1},
    {'hanzi': '睡觉', 'pinyin': 'shuìjiào', 'meaning': 'ngủ', 'hsk_level': 1},
    {'hanzi': '说', 'pinyin': 'shuō', 'meaning': 'nói', 'hsk_level': 1},
    {'hanzi': '说话', 'pinyin': 'shuōhuà', 'meaning': 'nói chuyện', 'hsk_level': 1},
    {'hanzi': '四', 'pinyin': 'sì', 'meaning': 'bốn góc', 'hsk_level': 1},
    {'hanzi': '岁', 'pinyin': 'suì', 'meaning': 'tuổi', 'hsk_level': 1},
    {'hanzi': '他', 'pinyin': 'tā', 'meaning': 'anh ấy, ông ấy', 'hsk_level': 1},
    {'hanzi': '它', 'pinyin': 'tā', 'meaning': 'đó', 'hsk_level': 1},
    {'hanzi': '她', 'pinyin': 'tā', 'meaning': 'cô ấy, bà ấy', 'hsk_level': 1},
    {'hanzi': '他们', 'pinyin': 'tāmen', 'meaning': 'họ', 'hsk_level': 1},
    {'hanzi': '它们', 'pinyin': 'tāmen', 'meaning': 'họ', 'hsk_level': 1},
    {'hanzi': '她们', 'pinyin': 'tāmen', 'meaning': 'họ', 'hsk_level': 1},
    {'hanzi': '太', 'pinyin': 'tài', 'meaning': 'quá', 'hsk_level': 1},
    {'hanzi': '天气', 'pinyin': 'tiānqì', 'meaning': 'thời tiết', 'hsk_level': 1},
    {'hanzi': '听', 'pinyin': 'tīng', 'meaning': 'nghe', 'hsk_level': 1},
    {'hanzi': '听见', 'pinyin': 'tīngjiàn', 'meaning': 'nghe thấy', 'hsk_level': 1},
    {'hanzi': '同学', 'pinyin': 'tóngxué', 'meaning': 'bạn học', 'hsk_level': 1},
    {'hanzi': '外', 'pinyin': 'wài', 'meaning': 'ngoài', 'hsk_level': 1},
    {'hanzi': '外边', 'pinyin': 'wàibian', 'meaning': 'ngoài kia', 'hsk_level': 1},
    {'hanzi': '玩', 'pinyin': 'wán', 'meaning': 'chơi', 'hsk_level': 1},
    {'hanzi': '晚', 'pinyin': 'wǎn', 'meaning': 'tối', 'hsk_level': 1},
    {'hanzi': '晚饭', 'pinyin': 'wǎnfàn', 'meaning': 'bữa tối', 'hsk_level': 1},
    {'hanzi': '晚上', 'pinyin': 'wǎnshang', 'meaning': 'tối', 'hsk_level': 1},
    {'hanzi': '问', 'pinyin': 'wèn', 'meaning': 'hỏi', 'hsk_level': 1},
    {'hanzi': '问题', 'pinyin': 'wèntí', 'meaning': 'vấn đề', 'hsk_level': 1},
    {'hanzi': '我', 'pinyin': 'wǒ', 'meaning': 'tôi', 'hsk_level': 1},
    {'hanzi': '我们', 'pinyin': 'wǒmen', 'meaning': 'chúng tôi', 'hsk_level': 1},
    {'hanzi': '五', 'pinyin': 'wǔ', 'meaning': 'năm', 'hsk_level': 1},
    {'hanzi': '午饭', 'pinyin': 'wǔfàn', 'meaning': 'bữa trưa', 'hsk_level': 1},
    {'hanzi': '喜欢', 'pinyin': 'xǐhuan', 'meaning': 'thích', 'hsk_level': 1},
    {'hanzi': '下', 'pinyin': 'xià', 'meaning': 'xuống', 'hsk_level': 1},
    {'hanzi': '下班', 'pinyin': 'xiàbān', 'meaning': 'đi làm', 'hsk_level': 1},
    {'hanzi': '下课', 'pinyin': 'xiàkè', 'meaning': 'đi học', 'hsk_level': 1},
    {'hanzi': '下午', 'pinyin': 'xiàwǔ', 'meaning': 'buổi chiều', 'hsk_level': 1},
    {'hanzi': '先生', 'pinyin': 'xiānsheng', 'meaning': 'ông, ngài', 'hsk_level': 1},
    {'hanzi': '现在', 'pinyin': 'xiànzài', 'meaning': 'bây giờ', 'hsk_level': 1},
    {'hanzi': '想', 'pinyin': 'xiǎng', 'meaning': 'nghĩ, muốn', 'hsk_level': 1},
    {'hanzi': '小', 'pinyin': 'xiǎo', 'meaning': 'nhỏ', 'hsk_level': 1},
    {'hanzi': '小朋友', 'pinyin': 'xiǎopéngyǒu', 'meaning': 'bạn nhỏ', 'hsk_level': 1},
    {'hanzi': '小时', 'pinyin': 'xiǎoshí', 'meaning': 'giờ', 'hsk_level': 1},
    {'hanzi': '小学', 'pinyin': 'xiǎoxué', 'meaning': 'học tiểu học', 'hsk_level': 1},
    {'hanzi': '小学生', 'pinyin': 'xiǎoxuéshēng', 'meaning': 'học sinh tiểu học', 'hsk_level': 1},
    {'hanzi': '些', 'pinyin': 'xiē', 'meaning': 'vài', 'hsk_level': 1},
    {'hanzi': '写', 'pinyin': 'xiě', 'meaning': 'viết', 'hsk_level': 1},
    {'hanzi': '谢谢', 'pinyin': 'xièxie', 'meaning': 'cảm ơn', 'hsk_level': 1},
    {'hanzi': '新', 'pinyin': 'xīn', 'meaning': 'mới', 'hsk_level': 1},
    {'hanzi': '星期', 'pinyin': 'xīngqī', 'meaning': 'tuần', 'hsk_level': 1},
    {'hanzi': '星期日', 'pinyin': 'xīngqīrì', 'meaning': 'thứ hai', 'hsk_level': 1},
    {'hanzi': '星期天', 'pinyin': 'xīngqītiān', 'meaning': 'chủ nhật', 'hsk_level': 1},
    {'hanzi': '休息', 'pinyin': 'xiūxi', 'meaning': 'ngơi nghỉ', 'hsk_level': 1},
    {'hanzi': '学生', 'pinyin': 'xuéshēng', 'meaning': 'học sinh', 'hsk_level': 1},
    {'hanzi': '学习', 'pinyin': 'xuéxí', 'meaning': 'học tập', 'hsk_level': 1},
    {'hanzi': '学校', 'pinyin': 'xuéxiào', 'meaning': 'trường học', 'hsk_level': 1},
    {'hanzi': '雪', 'pinyin': 'xuě', 'meaning': 'tuyết', 'hsk_level': 1},
    {'hanzi': '要', 'pinyin': 'yào', 'meaning': 'cần', 'hsk_level': 1},
    {'hanzi': '也', 'pinyin': 'yě', 'meaning': 'cũng', 'hsk_level': 1},
    {'hanzi': '一', 'pinyin': 'yī', 'meaning': 'một', 'hsk_level': 1},
    {'hanzi': '衣服', 'pinyin': 'yīfu', 'meaning': 'quần áo', 'hsk_level': 1},
    {'hanzi': '医生', 'pinyin': 'yīshēng', 'meaning': 'bác sĩ', 'hsk_level': 1},
    {'hanzi': '医院', 'pinyin': 'yīyuàn', 'meaning': 'bệnh viện', 'hsk_level': 1},
    {'hanzi': '一下', 'pinyin': 'yíxià', 'meaning': 'một chút', 'hsk_level': 1},
    {'hanzi': '椅子', 'pinyin': 'yǐzi', 'meaning': 'ghế', 'hsk_level': 1},
    {'hanzi': '一点儿', 'pinyin': 'yìdiǎnr', 'meaning': 'một chút', 'hsk_level': 1},
    {'hanzi': '一些', 'pinyin': 'yìxiē', 'meaning': 'một số', 'hsk_level': 1},
    {'hanzi': '有', 'pinyin': 'yǒu', 'meaning': 'có', 'hsk_level': 1},
    {'hanzi': '有的', 'pinyin': 'yǒude', 'meaning': 'có sẵn', 'hsk_level': 1},
    {'hanzi': '有点儿', 'pinyin': 'yǒudiǎnr', 'meaning': 'một chút', 'hsk_level': 1},
    {'hanzi': '有些', 'pinyin': 'yǒuxiē', 'meaning': 'một số', 'hsk_level': 1},
    {'hanzi': '元', 'pinyin': 'yuán', 'meaning': 'năm', 'hsk_level': 1},
    {'hanzi': '月', 'pinyin': 'yuè', 'meaning': 'tháng, mặt trăng', 'hsk_level': 1},
    {'hanzi': '再', 'pinyin': 'zài', 'meaning': 'lại', 'hsk_level': 1},
    {'hanzi': '在', 'pinyin': 'zài', 'meaning': 'ở, tại', 'hsk_level': 1},
    {'hanzi': '再见', 'pinyin': 'zàijiàn', 'meaning': 'tạm biệt', 'hsk_level': 1},
    {'hanzi': '早', 'pinyin': 'zǎo', 'meaning': 'sớm', 'hsk_level': 1},
    {'hanzi': '早饭', 'pinyin': 'zǎofàn', 'meaning': 'bữa sáng', 'hsk_level': 1},
    {'hanzi': '早上', 'pinyin': 'zǎoshang', 'meaning': 'sáng sớm', 'hsk_level': 1},
    {'hanzi': '怎么', 'pinyin': 'zěnme', 'meaning': 'làm sao', 'hsk_level': 1},
    {'hanzi': '怎么样', 'pinyin': 'zěnmeyàng', 'meaning': 'như thế nào', 'hsk_level': 1},
    {'hanzi': '找', 'pinyin': 'zhǎo', 'meaning': 'tìm kiếm', 'hsk_level': 1},
    {'hanzi': '这', 'pinyin': 'zhè', 'meaning': 'Đây, này', 'hsk_level': 1},
    {'hanzi': '这边', 'pinyin': 'zhèbiān', 'meaning': 'đây', 'hsk_level': 1},
    {'hanzi': '这个', 'pinyin': 'zhège', 'meaning': 'đây', 'hsk_level': 1},
    {'hanzi': '这里', 'pinyin': 'zhèlǐ', 'meaning': 'đây', 'hsk_level': 1},
    {'hanzi': '这儿', 'pinyin': 'zhèr', 'meaning': 'đây', 'hsk_level': 1},
    {'hanzi': '这些', 'pinyin': 'zhèxiē', 'meaning': 'những', 'hsk_level': 1},
    {'hanzi': '真', 'pinyin': 'zhēn', 'meaning': 'thật', 'hsk_level': 1},
    {'hanzi': '正在', 'pinyin': 'zhèngzài', 'meaning': 'đang', 'hsk_level': 1},
    {'hanzi': '知道', 'pinyin': 'zhīdào', 'meaning': 'biết', 'hsk_level': 1},
    {'hanzi': '中国', 'pinyin': 'Zhōngguó', 'meaning': 'Trung Quốc', 'hsk_level': 1},
    {'hanzi': '中文', 'pinyin': 'Zhōngwén', 'meaning': 'tiếng Trung', 'hsk_level': 1},
    {'hanzi': '中午', 'pinyin': 'zhōngwǔ', 'meaning': 'buổi trưa', 'hsk_level': 1},
    {'hanzi': '中学', 'pinyin': 'zhōngxué', 'meaning': 'trung học', 'hsk_level': 1},
    {'hanzi': '中学生', 'pinyin': 'zhōngxuéshēng', 'meaning': 'học sinh trung học', 'hsk_level': 1},
    {'hanzi': '住', 'pinyin': 'zhù', 'meaning': 'sống, cư trú', 'hsk_level': 1},
    {'hanzi': '桌子', 'pinyin': 'zhuōzi', 'meaning': 'bàn', 'hsk_level': 1},
    {'hanzi': '昨天', 'pinyin': 'zuótiān', 'meaning': 'hôm qua', 'hsk_level': 1},
    {'hanzi': '做', 'pinyin': 'zuò', 'meaning': 'làm', 'hsk_level': 1},
    {'hanzi': '做饭', 'pinyin': 'zuò', 'meaning': 'nấu ăn', 'hsk_level': 1},
    ],
    2: [
        {"hanzi": "把", "pinyin": "bǎ", "meaning": "giới từ chỉ tác động lên đối tượng", "hsk_level": 2},
        {"hanzi": "班", "pinyin": "bān", "meaning": "lớp học, ca làm", "hsk_level": 2},
        {"hanzi": "搬", "pinyin": "bān", "meaning": "chuyển đồ, dọn nhà", "hsk_level": 2},
        {"hanzi": "帮助", "pinyin": "bāngzhù", "meaning": "giúp đỡ, hỗ trợ", "hsk_level": 2},
        {"hanzi": "比", "pinyin": "bǐ", "meaning": "so sánh, hơn", "hsk_level": 2},
        {"hanzi": "别", "pinyin": "bié", "meaning": "đừng, chớ", "hsk_level": 2},
        {"hanzi": "病", "pinyin": "bìng", "meaning": "bệnh, ốm", "hsk_level": 2},
        {"hanzi": "才", "pinyin": "cái", "meaning": "mới, vừa mới (nhấn mạnh)", "hsk_level": 2},
        {"hanzi": "层", "pinyin": "céng", "meaning": "tầng, lớp", "hsk_level": 2},
        {"hanzi": "长", "pinyin": "cháng", "meaning": "dài, lâu", "hsk_level": 2},
        {"hanzi": "唱歌", "pinyin": "chànggē", "meaning": "hát (bài hát)", "hsk_level": 2},
        {"hanzi": "出", "pinyin": "chū", "meaning": "ra, xuất, ra ngoài", "hsk_level": 2},
        {"hanzi": "穿", "pinyin": "chuān", "meaning": "mặc (quần áo)", "hsk_level": 2},
        {"hanzi": "从", "pinyin": "cóng", "meaning": "từ (điểm xuất phát)", "hsk_level": 2},
        {"hanzi": "错", "pinyin": "cuò", "meaning": "sai, nhầm, lỗi", "hsk_level": 2},
        {"hanzi": "打篮球", "pinyin": "dǎ lánqiú", "meaning": "chơi bóng rổ", "hsk_level": 2},
        {"hanzi": "但是", "pinyin": "dànshì", "meaning": "nhưng, nhưng mà", "hsk_level": 2},
        {"hanzi": "道", "pinyin": "dào", "meaning": "đường, con đường, đạo", "hsk_level": 2},
        {"hanzi": "得", "pinyin": "de/děi/dé", "meaning": "trợ từ/phải/được", "hsk_level": 2},
        {"hanzi": "等", "pinyin": "děng", "meaning": "đợi, chờ", "hsk_level": 2},
        {"hanzi": "地方", "pinyin": "dìfang", "meaning": "nơi chốn, địa điểm", "hsk_level": 2},
        {"hanzi": "懂", "pinyin": "dǒng", "meaning": "hiểu, thông", "hsk_level": 2},
        {"hanzi": "对", "pinyin": "duì", "meaning": "đúng, phải, đối với", "hsk_level": 2},
        {"hanzi": "房间", "pinyin": "fángjiān", "meaning": "phòng (trong nhà)", "hsk_level": 2},
        {"hanzi": "放", "pinyin": "fàng", "meaning": "đặt, thả, bỏ vào", "hsk_level": 2},
        {"hanzi": "服务员", "pinyin": "fúwùyuán", "meaning": "nhân viên phục vụ", "hsk_level": 2},
        {"hanzi": "贵", "pinyin": "guì", "meaning": "đắt, quý", "hsk_level": 2},
        {"hanzi": "过", "pinyin": "guò", "meaning": "qua, đã từng (trải qua)", "hsk_level": 2},
        {"hanzi": "还", "pinyin": "hái", "meaning": "vẫn còn, còn nữa", "hsk_level": 2},
        {"hanzi": "孩子", "pinyin": "háizi", "meaning": "trẻ em, đứa con", "hsk_level": 2},
    ],
    3: [
        {"hanzi": "阿姨", "pinyin": "āyí", "meaning": "dì, cô, bác gái", "hsk_level": 3},
        {"hanzi": "啊", "pinyin": "a", "meaning": "ồ, à (thán từ)", "hsk_level": 3},
        {"hanzi": "办法", "pinyin": "bànfǎ", "meaning": "cách làm, biện pháp", "hsk_level": 3},
        {"hanzi": "办公室", "pinyin": "bàngōngshì", "meaning": "văn phòng", "hsk_level": 3},
        {"hanzi": "包", "pinyin": "bāo", "meaning": "túi, gói, bao gồm", "hsk_level": 3},
        {"hanzi": "饱", "pinyin": "bǎo", "meaning": "no (bụng)", "hsk_level": 3},
        {"hanzi": "北方", "pinyin": "běifāng", "meaning": "phương Bắc, miền Bắc", "hsk_level": 3},
        {"hanzi": "变化", "pinyin": "biànhuà", "meaning": "thay đổi, biến hóa", "hsk_level": 3},
        {"hanzi": "表示", "pinyin": "biǎoshì", "meaning": "biểu thị, thể hiện", "hsk_level": 3},
        {"hanzi": "冰箱", "pinyin": "bīngxiāng", "meaning": "tủ lạnh", "hsk_level": 3},
        {"hanzi": "不但", "pinyin": "bùdàn", "meaning": "không chỉ (mà còn)", "hsk_level": 3},
        {"hanzi": "节日", "pinyin": "jiérì", "meaning": "ngày lễ, ngày tết", "hsk_level": 3},
        {"hanzi": "经常", "pinyin": "jīngcháng", "meaning": "thường xuyên, hay", "hsk_level": 3},
        {"hanzi": "进", "pinyin": "jìn", "meaning": "vào, tiến vào", "hsk_level": 3},
        {"hanzi": "近", "pinyin": "jìn", "meaning": "gần, cận", "hsk_level": 3},
        {"hanzi": "旧", "pinyin": "jiù", "meaning": "cũ, lỗi thời", "hsk_level": 3},
        {"hanzi": "句子", "pinyin": "jùzi", "meaning": "câu (văn)", "hsk_level": 3},
        {"hanzi": "开始", "pinyin": "kāishǐ", "meaning": "bắt đầu, khởi đầu", "hsk_level": 3},
        {"hanzi": "渴", "pinyin": "kě", "meaning": "khát (nước)", "hsk_level": 3},
        {"hanzi": "空调", "pinyin": "kōngtiáo", "meaning": "điều hòa không khí", "hsk_level": 3},
        {"hanzi": "口", "pinyin": "kǒu", "meaning": "miệng, cửa, người (đơn vị)", "hsk_level": 3},
        {"hanzi": "哭", "pinyin": "kū", "meaning": "khóc", "hsk_level": 3},
        {"hanzi": "快乐", "pinyin": "kuàilè", "meaning": "vui vẻ, hạnh phúc", "hsk_level": 3},
        {"hanzi": "累", "pinyin": "lèi", "meaning": "mệt mỏi", "hsk_level": 3},
        {"hanzi": "离", "pinyin": "lí", "meaning": "cách (khoảng cách), xa", "hsk_level": 3},
        {"hanzi": "脸", "pinyin": "liǎn", "meaning": "mặt, khuôn mặt", "hsk_level": 3},
        {"hanzi": "练习", "pinyin": "liànxí", "meaning": "luyện tập, bài tập", "hsk_level": 3},
        {"hanzi": "楼", "pinyin": "lóu", "meaning": "tòa nhà, tầng lầu", "hsk_level": 3},
        {"hanzi": "路", "pinyin": "lù", "meaning": "đường, con đường", "hsk_level": 3},
        {"hanzi": "旅游", "pinyin": "lǚyóu", "meaning": "du lịch", "hsk_level": 3},
    ],
    4: [
        {"hanzi": "爱好", "pinyin": "àihào", "meaning": "sở thích, đam mê", "hsk_level": 4},
        {"hanzi": "安排", "pinyin": "ānpái", "meaning": "sắp xếp, bố trí", "hsk_level": 4},
        {"hanzi": "安全", "pinyin": "ānquán", "meaning": "an toàn, bình an", "hsk_level": 4},
        {"hanzi": "按时", "pinyin": "ànshí", "meaning": "đúng giờ, theo đúng thời gian", "hsk_level": 4},
        {"hanzi": "百分之", "pinyin": "bǎifēnzhī", "meaning": "phần trăm", "hsk_level": 4},
        {"hanzi": "保护", "pinyin": "bǎohù", "meaning": "bảo vệ, bảo hộ", "hsk_level": 4},
        {"hanzi": "抱怨", "pinyin": "bàoyuàn", "meaning": "phàn nàn, oán trách", "hsk_level": 4},
        {"hanzi": "被", "pinyin": "bèi", "meaning": "bị (bị động)", "hsk_level": 4},
        {"hanzi": "笔记本", "pinyin": "bǐjìběn", "meaning": "vở ghi chú, laptop", "hsk_level": 4},
        {"hanzi": "毕业", "pinyin": "bìyè", "meaning": "tốt nghiệp", "hsk_level": 4},
        {"hanzi": "表演", "pinyin": "biǎoyǎn", "meaning": "biểu diễn, diễn xuất", "hsk_level": 4},
        {"hanzi": "表扬", "pinyin": "biǎoyáng", "meaning": "khen ngợi, biểu dương", "hsk_level": 4},
        {"hanzi": "参观", "pinyin": "cānguān", "meaning": "tham quan, thăm viếng", "hsk_level": 4},
        {"hanzi": "尝", "pinyin": "cháng", "meaning": "nếm thử, thử", "hsk_level": 4},
        {"hanzi": "成功", "pinyin": "chénggōng", "meaning": "thành công", "hsk_level": 4},
        {"hanzi": "城市", "pinyin": "chéngshì", "meaning": "thành phố, đô thị", "hsk_level": 4},
        {"hanzi": "诚实", "pinyin": "chéngshí", "meaning": "thành thật, trung thực", "hsk_level": 4},
        {"hanzi": "重要", "pinyin": "zhòngyào", "meaning": "quan trọng", "hsk_level": 4},
        {"hanzi": "发现", "pinyin": "fāxiàn", "meaning": "phát hiện, khám phá", "hsk_level": 4},
        {"hanzi": "方法", "pinyin": "fāngfǎ", "meaning": "phương pháp, cách thức", "hsk_level": 4},
        {"hanzi": "复杂", "pinyin": "fùzá", "meaning": "phức tạp", "hsk_level": 4},
        {"hanzi": "感谢", "pinyin": "gǎnxiè", "meaning": "cảm ơn, cảm tạ", "hsk_level": 4},
        {"hanzi": "根据", "pinyin": "gēnjù", "meaning": "căn cứ vào, dựa theo", "hsk_level": 4},
        {"hanzi": "故事", "pinyin": "gùshi", "meaning": "câu chuyện", "hsk_level": 4},
        {"hanzi": "关系", "pinyin": "guānxi", "meaning": "quan hệ, mối liên hệ", "hsk_level": 4},
        {"hanzi": "管理", "pinyin": "guǎnlǐ", "meaning": "quản lý, quản trị", "hsk_level": 4},
        {"hanzi": "规定", "pinyin": "guīdìng", "meaning": "quy định, điều lệ", "hsk_level": 4},
        {"hanzi": "国际", "pinyin": "guójì", "meaning": "quốc tế", "hsk_level": 4},
        {"hanzi": "过去", "pinyin": "guòqù", "meaning": "quá khứ, ngày xưa", "hsk_level": 4},
        {"hanzi": "害怕", "pinyin": "hàipà", "meaning": "sợ hãi, lo lắng", "hsk_level": 4},
    ],
    5: [
        {"hanzi": "爱护", "pinyin": "àihù", "meaning": "bảo vệ, chăm sóc yêu thương", "hsk_level": 5},
        {"hanzi": "爱惜", "pinyin": "àixī", "meaning": "trân trọng, quý trọng", "hsk_level": 5},
        {"hanzi": "安慰", "pinyin": "ānwèi", "meaning": "an ủi, vỗ về", "hsk_level": 5},
        {"hanzi": "暗", "pinyin": "àn", "meaning": "tối, ám, ngầm", "hsk_level": 5},
        {"hanzi": "熬夜", "pinyin": "áoyè", "meaning": "thức khuya, thức đêm", "hsk_level": 5},
        {"hanzi": "把握", "pinyin": "bǎwò", "meaning": "nắm chắc, chắc chắn", "hsk_level": 5},
        {"hanzi": "摆", "pinyin": "bǎi", "meaning": "bày, đặt, xếp", "hsk_level": 5},
        {"hanzi": "版本", "pinyin": "bǎnběn", "meaning": "phiên bản, bản (sách)", "hsk_level": 5},
        {"hanzi": "辩论", "pinyin": "biànlùn", "meaning": "tranh luận, biện luận", "hsk_level": 5},
        {"hanzi": "表达", "pinyin": "biǎodá", "meaning": "bày tỏ, diễn đạt", "hsk_level": 5},
        {"hanzi": "表面", "pinyin": "biǎomiàn", "meaning": "bề mặt, bên ngoài", "hsk_level": 5},
        {"hanzi": "不得不", "pinyin": "bùdébù", "meaning": "bất đắc dĩ, buộc phải", "hsk_level": 5},
        {"hanzi": "不免", "pinyin": "bùmiǎn", "meaning": "không tránh khỏi, không khỏi", "hsk_level": 5},
        {"hanzi": "财富", "pinyin": "cáifù", "meaning": "tài sản, của cải", "hsk_level": 5},
        {"hanzi": "策略", "pinyin": "cèlüè", "meaning": "chiến lược, sách lược", "hsk_level": 5},
        {"hanzi": "差距", "pinyin": "chājù", "meaning": "khoảng cách, sự chênh lệch", "hsk_level": 5},
        {"hanzi": "长期", "pinyin": "chángqī", "meaning": "lâu dài, dài hạn", "hsk_level": 5},
        {"hanzi": "趋势", "pinyin": "qūshì", "meaning": "xu hướng, xu thế", "hsk_level": 5},
        {"hanzi": "认为", "pinyin": "rènwéi", "meaning": "cho rằng, nhận thấy", "hsk_level": 5},
        {"hanzi": "实现", "pinyin": "shíxiàn", "meaning": "thực hiện, đạt được", "hsk_level": 5},
        {"hanzi": "市场", "pinyin": "shìchǎng", "meaning": "thị trường", "hsk_level": 5},
        {"hanzi": "影响", "pinyin": "yǐngxiǎng", "meaning": "ảnh hưởng, tác động", "hsk_level": 5},
        {"hanzi": "主要", "pinyin": "zhǔyào", "meaning": "chủ yếu, chính", "hsk_level": 5},
        {"hanzi": "专业", "pinyin": "zhuānyè", "meaning": "chuyên ngành, chuyên nghiệp", "hsk_level": 5},
        {"hanzi": "资料", "pinyin": "zīliào", "meaning": "tài liệu, dữ liệu", "hsk_level": 5},
        {"hanzi": "自然", "pinyin": "zìrán", "meaning": "tự nhiên, thiên nhiên", "hsk_level": 5},
        {"hanzi": "总结", "pinyin": "zǒngjié", "meaning": "tổng kết, tóm tắt", "hsk_level": 5},
        {"hanzi": "组织", "pinyin": "zǔzhī", "meaning": "tổ chức", "hsk_level": 5},
        {"hanzi": "作者", "pinyin": "zuòzhě", "meaning": "tác giả", "hsk_level": 5},
        {"hanzi": "优秀", "pinyin": "yōuxiù", "meaning": "xuất sắc, ưu tú", "hsk_level": 5},
    ],
    6: [
        {"hanzi": "爱戴", "pinyin": "àidài", "meaning": "kính yêu, tôn kính", "hsk_level": 6},
        {"hanzi": "阐述", "pinyin": "chǎnshù", "meaning": "trình bày rõ ràng, giải thích", "hsk_level": 6},
        {"hanzi": "倡导", "pinyin": "chàngdǎo", "meaning": "đề xuất, khởi xướng", "hsk_level": 6},
        {"hanzi": "沉默", "pinyin": "chénmò", "meaning": "im lặng, trầm tĩnh", "hsk_level": 6},
        {"hanzi": "承担", "pinyin": "chéngdān", "meaning": "gánh chịu, đảm nhận", "hsk_level": 6},
        {"hanzi": "充分", "pinyin": "chōngfèn", "meaning": "đầy đủ, sung mãn", "hsk_level": 6},
        {"hanzi": "抽象", "pinyin": "chōuxiàng", "meaning": "trừu tượng, mơ hồ", "hsk_level": 6},
        {"hanzi": "传统", "pinyin": "chuántǒng", "meaning": "truyền thống", "hsk_level": 6},
        {"hanzi": "创新", "pinyin": "chuàngxīn", "meaning": "đổi mới, sáng tạo", "hsk_level": 6},
        {"hanzi": "辞职", "pinyin": "cízhí", "meaning": "từ chức, nghỉ việc", "hsk_level": 6},
        {"hanzi": "存在", "pinyin": "cúnzài", "meaning": "tồn tại, hiện hữu", "hsk_level": 6},
        {"hanzi": "从而", "pinyin": "cóng'ér", "meaning": "từ đó, do vậy", "hsk_level": 6},
        {"hanzi": "达到", "pinyin": "dádào", "meaning": "đạt đến, đạt được", "hsk_level": 6},
        {"hanzi": "道德", "pinyin": "dàodé", "meaning": "đạo đức", "hsk_level": 6},
        {"hanzi": "独特", "pinyin": "dútè", "meaning": "độc đáo, đặc biệt", "hsk_level": 6},
        {"hanzi": "发展", "pinyin": "fāzhǎn", "meaning": "phát triển", "hsk_level": 6},
        {"hanzi": "繁荣", "pinyin": "fánróng", "meaning": "phồn thịnh, hưng thịnh", "hsk_level": 6},
        {"hanzi": "改革", "pinyin": "gǎigé", "meaning": "cải cách, đổi mới", "hsk_level": 6},
        {"hanzi": "构建", "pinyin": "gòujiàn", "meaning": "xây dựng, kiến tạo", "hsk_level": 6},
        {"hanzi": "归纳", "pinyin": "guīnà", "meaning": "quy nạp, tổng hợp", "hsk_level": 6},
        {"hanzi": "核心", "pinyin": "héxīn", "meaning": "hạt nhân, cốt lõi", "hsk_level": 6},
        {"hanzi": "竞争", "pinyin": "jìngzhēng", "meaning": "cạnh tranh", "hsk_level": 6},
        {"hanzi": "可持续", "pinyin": "kě chíxù", "meaning": "bền vững, duy trì được", "hsk_level": 6},
        {"hanzi": "理念", "pinyin": "lǐniàn", "meaning": "lý niệm, quan niệm", "hsk_level": 6},
        {"hanzi": "历史", "pinyin": "lìshǐ", "meaning": "lịch sử", "hsk_level": 6},
        {"hanzi": "模式", "pinyin": "móshì", "meaning": "mô hình, mô thức", "hsk_level": 6},
        {"hanzi": "批判", "pinyin": "pīpàn", "meaning": "phê phán, phê bình", "hsk_level": 6},
        {"hanzi": "确保", "pinyin": "quèbǎo", "meaning": "đảm bảo, chắc chắn", "hsk_level": 6},
        {"hanzi": "文明", "pinyin": "wénmíng", "meaning": "văn minh, nền văn hóa", "hsk_level": 6},
        {"hanzi": "综合", "pinyin": "zōnghé", "meaning": "tổng hợp, toàn diện", "hsk_level": 6},
    ],
}


def get_words_for_level(level: int) -> list:
    """Return list of words for a given HSK level."""
    return HSK_WORDS.get(level, [])


def get_word_at_index(level: int, index: int) -> dict:
    """Get word at index for a level, wrapping around if needed."""
    words = get_words_for_level(level)
    if not words:
        return None
    return words[index % len(words)]


def get_all_words() -> list:
    """Return all words from all levels."""
    all_words = []
    for level_words in HSK_WORDS.values():
        all_words.extend(level_words)
    return all_words


def find_word_by_hanzi(hanzi: str) -> dict:
    """Find a word dict by its hanzi string."""
    for word in get_all_words():
        if word["hanzi"] == hanzi:
            return word
    return None
